[package]
name = "aurguard-core"
description = "Static analysis engine for AUR package repositories"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
regex.workspace = true
serde.workspace = true
sha2.workspace = true
walkdir.workspace = true
